#----------------------------------------
# Configuration du site
# http://jekyllrb.com/docs/configuration/
#----------------------------------------

destination: _site
author: Ulrich GEro
email: hello@offdesign.co
location: Worldwide
title: Artsylvestr official website 
language: "en"
baseurl: ""
url: "https://blog.kareeba.com"
description: "Kareeba blog is the community of African Fashion Designer & Accesories Makers. From Africa to the Worldwide"
keywords: [Kareeba, African Wax, dashiki, afro tips, marketplace, kareeba, accesories, african clothes, made in africa]

timezone: London

#------------
# disques comment system
#------------
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: kareebablog
#------------
# Social Link
#------------

twitter: https://www.twitter.com/kareebaco
linkedin: https://www.linkedin.com/kareebaco
facebook: https://www.facebook.com/kareebaco
instagram: https://www.instagram.com/kareebaco

#-----------------------
# configuration du build
#-----------------------

encoding: utf-8
markdown: kramdown
permalink: /:slug/

#---------------------
# Configuration plugin
#---------------------

plugins:
  - jekyll-paginate
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag

#--------
#authors setting
#---------
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

#----------
#gem
#----------

jekyll-minifier:
  exclude: 'atom.xml'
  uglifier_args:
    harmony: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  compress_javascript: true

paginate: 2
paginate_path: "/blog/page:num/"

include: ['_categories']
#---------------------
# configuration assets
#---------------------

sass:
  load_paths:
    _sass
    node_modules
  style: compressed

#-----------------------
# configuration includes
#-----------------------

includes_dir : _includes
layouts_dir : _layouts

#-----------------------
# configuration excludes
#-----------------------

# File excludes
exclude:
  - .sass-cache
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - netlify.toml
  - node_modules
  - package.json
  - package-lock.json

jekyll_admin:
  hidden_links:
    - staticfiles
  homepage: "posts"

collections:
  posts:
    output: true
    sidebar_label: Articles

livereload: true
