#----------------------------------------
# Configuration du site
# http://jekyllrb.com/docs/configuration/
#----------------------------------------

destination: _site
author: Ulrich Gero
email: hello@offdesign.co
location: Worldwide
title: Artsylvestr official website 
language: "en"
baseurl: "/"
url: "https://artsylvestr.com/"
description: "Artsylvestr official website where the Camerun born and Italy based painter share his journey."
keywords: [Artsylvestr, Painting, Quadri, Afro Italian, afro tips, accesories,  made in africa]

timezone: London



twitter: https://twitter.com/JosephDesire11

facebook: https://www.facebook.com/desire.joseph.1


#-----------------------
# configuration du build
#-----------------------

encoding: utf-8
markdown: kramdown
permalink: /:slug/

#---------------------
# Configuration plugin
#---------------------

plugins:
  - jekyll-paginate
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag


#----------
#gem
#----------

jekyll-minifier:
  exclude: 'atom.xml'
  uglifier_args:
    harmony: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  compress_javascript: true

paginate: 2
paginate_path: "/blog/page:num/"

include: ['_categories']
#---------------------
# configuration assets
#---------------------

sass:
  load_paths:
    _sass
    node_modules
  style: compressed

#-----------------------
# configuration includes
#-----------------------

includes_dir : _includes
layouts_dir : _layouts

#-----------------------
# configuration excludes
#-----------------------

# File excludes
exclude:
  - .sass-cache
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - netlify.toml
  - node_modules
  - package.json
  - package-lock.json

jekyll_admin:
  hidden_links:
    - staticfiles
  homepage: "posts"

collections:
  posts:
    output: true
    sidebar_label: Articles

livereload: true
